name: React CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      # Checkout kode
      - uses: actions/checkout@v4

      # Setup Node 20 + pnpm
      - name: Use Node.js ${{ matrix.node-version }} with pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9              # versi pnpm yang ingin kamu pakai
          run_install: false
          node-version: ${{ matrix.node-version }}

      # Cache store pnpm
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store/v3
          key: pnpm-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-${{ matrix.node-version }}-

      # Install dependency
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      # Jalankan unit test
      - name: Run unit tests
        run: pnpm run test
