name: React Unit Test CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      # 1) Check out your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Install pnpm and set Node 20
      - name: Set up Node.js ${{ matrix.node-version }} + pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9 # choose the pnpm version you want
          run_install: false # we’ll run it manually below
          node-version: ${{ matrix.node-version }}

      # 3) Restore / save pnpm store for faster builds
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store/v3
          key: pnpm-store-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-${{ matrix.node-version }}-

      # 4) Install project dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5) (Optional) Build the project
      - name: Build the project
        run: pnpm run build --if-present

      # 6) Run the unit tests
      - name: Run tests
        run: pnpm run test
